name = "InteractivePresentations"
uuid = "e0adfb67-6a19-4170-8314-b8ef321cb235"
authors = ["Jochen Krattenmacher"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
